### ISSUE TITLE
Provide option to trigger methods even when an input field is focused

### ISSUE THREAD

**Issue by jeffijoe** [glortho/react-keydown#22]
If an input field has focus in the component, the handler is not triggered.

I am using the decorator method.

**Comment by glortho** [comment]
Thanks for the report @jeffijoe . This is by design (see [here](https://github.com/glortho/react-keydown/blob/master/src/event_handlers.js#L60)*), so that shortcuts don't interfere with user input, and because it's easy just to add `onKeyDown` to input fields if you want to capture keystrokes there.

Though looking back at this it occurred to me that it might be nice if a decorated method also acted like a key filter for handlers bound via `onKeyDown` also. To be considered. In fact, I'll rename this and add a tag, if that's okay with you.

*You'll note that I've added a bypass here on the `ctrl` key, so that `ctrl + <whatever>` shortcuts should in fact work on input fields, since it's arguably the one modifier key that we never or rarely use to modify text input.

**Comment by jeffijoe** [comment]
Perhaps something like:

``` js
@keydown(Keys.esc, { force: true })
myMethod() {}
```

So the last parameter, if an object, would be treated as an options object. The `force` could override the previously mentioned behavior.

What do you think?

**Comment by glortho** [comment]
Yeah it's worth considering something like this. I'd probably want it to be more explicit, along the lines of `triggerOnInputs: true`, or `onInputKeyDown: true`, though I'm not sure how I feel about this compared to an `onKeyDown` solution with the decorator acting in that case as a filter. The latter is a little extra work, and feels like it mixes methodologies, but it's also more explicit – you don't have to comb through methods + components to figure out who is hijacking keystrokes from input fields – and it may reduce complexity in cases where someone may have both a `triggerOnInputs` option set in a decorator as well as an `onKeyDown` handler.

Maybe the answer for now is to provide both - relatively easily done - and track usability feedback. I can probably get to this later tonight.

**Comment by jeffijoe** [comment]
Awesome :+1:

**Comment by glortho** [comment]
@jeffijoe as of 1.6.0 i've done the second one, where you can add `onKeyDown` to your input, specifying the handler that you've decorated with `@keydown( myKeys )`. this is experimental so i'm not documenting it yet, but it seems to work. though it's maybe not your first choice of how to handle this, it'd be great to get your feedback as to whether and how well it works.

i'll get to the other approach, passing in the option, by end of tomorrow.

**Comment by jeffijoe** [comment]
Is it on npm? And do you have an example of how I can achieve my goal with the newly added feature?

**Comment by glortho** [comment]
@jeffijoe yes 1.6.0 is published. You can try:

```
class MyClass extends React.Component {
  @keydown( 'a' )
  myMethod( event ) {
    console.log( event ); // should log on 'a' keystroke whether input is focused or not
  }

  render() {
    return <input onKeyDown={ this.myMethod } />;
  }
}
```

**Comment by glortho** [comment]
Note that this may be a desirable solution only when you want a particular keybinding to work in a particular input. If you want a binding to work across any number of inputs, you could spread `{ onKeyDown: this.myHandler }` into each of them, but it's probably better to give it a `ctrl` modifier, or wait for the brute force option coming soon (referenced above).

**Comment by jeffijoe** [comment]
Basically, what I need is to catch the Esc key regardless if my input is focused or not - if the control hosting the input has focus (which includes the input itself) I need to intercept Esc keys. How would I do that?

**Comment by glortho** [comment]
@jeffijoe it should work to just replace 'a' with 'esc' in my example. Let me know if that doesn't work.

**Comment by jeffijoe** [comment]
Oh, so you're not filtering out inputs anymore?

**Comment by jeffijoe** [comment]
In https://github.com/glortho/react-keydown/issues/22#issuecomment-221266609 the onKeyDown for the input would trigger on all keys - I would need to just have it trigger on Esc only

**Comment by glortho** [comment]
1.6.0 lets you override that behavior by adding an explicit `onKeyDown` binding to your input.

See here: https://github.com/glortho/react-keydown/blob/master/src/decorators/method_decorator.js#L40-L48

And here: https://github.com/glortho/react-keydown/blob/master/src/event_handlers.js#L38-L47

In this case `@keydown` acts as a filter, so that only the keys you've declared in the decorator will trigger the method.

**Comment by glortho** [comment]
Ah but looking at that code I see that you wouldn't be able to call this from elsewhere. Fixing.

**Comment by jeffijoe** [comment]
But `onKeyDown` is a regular DOM event, so the `@keydown` decorator then catches it and triggers the method if it matches?

**Comment by glortho** [comment]
Yes, when you provide your decorated method as the handler for the `onKeyDown` binding, the decorator intercepts the event and tries to match it to the declared keys. If no match is found it's a no-op.

**Comment by jeffijoe** [comment]
@glortho that's brilliant! Will try it tomorrow.

**Comment by jeffijoe** [comment]
It works with class ethods, but if I use

```
@keydown(Keys.ESC)
myMethod = () => {
};
```

The method is triggered regardless of the key.

**Comment by glortho** [comment]
Is that a function or an instance field? Functions are not supported in the (highly fluid) decorator spec, and instance fields are also highly experimental, so there is no support for them yet.

For functions you can try `const myMethod = keydown( Keys.ESC )( function() { ... } )` but react-keydown will currently expect that function arg to be a stateless functional component and will thus wrap it in a higher-order component.

For further conversation on this subject you may want to open a different issue, since this is unrelated to input fields.

**Comment by jeffijoe** [comment]
What's odd is that the shortcut actually does work, just not within the input. But I can live with this, thanks for implementing!
