### ISSUE TITLE
Array.from(arr) is causing exception in IE11

### ISSUE THREAD

**Issue by ronib** [glortho/react-keydown#29]
dist/store.js contains Array.from uses, which is not support by IE11.
Thanks!

**Comment by k7sleeper** [comment]
Why do you include a polyfill in the library? It unnecessarily increases code size!
In IE11, also `Symbol` is missing. So including `<script src="vendor/core.js"></script>` solves the missing symbol 'Symbol' as well as missing `Array.from`.

From my point of view it should be stated in the readme of this module that the browser must be ES6 compatible so that everyone knows to include something like `<script src="vendor/core.js"></script>` in IE11 or other older browsers.
