### ISSUE TITLE
Support for "delete" key?

### ISSUE THREAD

**Issue by machineghost** [glortho/react-keydown#36]
I recently tried to do:

    @keydown('delete')

but it doesn't appear to be supported.  Of course:

    @keydown(46) // 46 == delete

does still work, but if it's not too much trouble could you please add an "alias" for delete?

**Comment by glortho** [comment]
Ah okay. If you'd like you could add that to lib/keys and I'll merge. Otherwise I'll be back in the office tomorrow. 

On Wed, Nov 9, 2016 at 7:28 PM -0500, "Jeremy Walker" notifications@github.com wrote:

I recently tried to do:
@keydown('delete')

but it doesn't appear to be supported.  Of course:
@keydown(46) // 46 == delete

does still work, but if it's not too much trouble could you please add an "alias" for delete?

**Comment by machineghost** [comment]
I just went to do it and it looks like you already made the change.  Thanks.

**Comment by strataga** [comment]
I just tried 'del' and 'delete' and 46, but it does not work for me.

The docs say: "enter (aka return), tab, up, down, left, right, space, backspace"

I currently have the following keys above my function and the others besides delete work fine.

`@keydown('up', 'down', 'tab', 'shift+tab', 'enter', 'delete')`

**Comment by strataga** [comment]
ok well it appears that the 'delete' key on mac keyboard is the 'backspace' in the api.
