### ISSUE TITLE
Not working keydown when it nested multilevel

### ISSUE THREAD

**Issue by ashokkumarsand** [glortho/react-keydown#46]
```
<MyComp1 having keydown>
 <1>
.
.
 <n> having keydown scoped </n>
.
.
</1>
</MyComp>

```
In this scenario keydown is not working

**Comment by glortho** [comment]
@ashokkumarsand are you saying your code is like this?
```javascript
<MyComp> // has @keydown decorator
  <OneComp>
    <TwoComp /> // has @keydownScoped on a method
  </OneComp>
</MyComp>
```
If so, are you doing something like `React.cloneElement( children, ...otherProps )` inside of `MyComp.render()` and `OneComp.render()`? if not, the `keydown` prop won't make it down to `TwoComp`. I've considered switching over to the `context` API so that you don't have to explicitly pass props down, but that's still exploratory so it won't happen right away.

**Comment by ashokkumarsand** [comment]
@glortho Yeah i need like that. are we having some kind of hack which we can do. also it not focusing elements

**Comment by glortho** [comment]
These are really React questions so I recommend taking them to stackoverflow.com. You will surely get lots of answers to your questions there!






On Sun, Mar 26, 2017 at 11:56 PM -0400, "ashokkumarsand" <notifications@github.com> wrote:












@glortho Yeah i need like that. are we having some kind of hack which we can do. also it not focusing elements

**Comment by ashokkumarsand** [comment]
@glortho Thank you for giving your precious time.

**Comment by glortho** [comment]
No problem @ashokkumarsand !
