### ISSUE TITLE
Conditionally listen to key events

### ISSUE THREAD

**Issue by strataga** [glortho/react-keydown#52]
Let's say I have a list of items that I am rendering on a page. Each item is a component. Inside that component I am listening for key events, but I only want to listen when that component has a prop passed in called isSelected.

As it stands now, all of those components in the list are listening and I want to prevent that.

The following handler should only fire when this.props.isSelected === true:

`
       @keydown('up','down')
        handleKeyDown(e){
           console.log('handleKeyDown', e);
           e.preventDefault();
        }
`

**Comment by glortho** [comment]
I think I understand what you're looking for @appjitsu. There isn't yet support for conditional binding, but you can do one of these:

```javascript
@keydown('up','down')
handleKeyDown(e) {
  if ( this.props.isSelected ) {
    console.log('handleKeyDown', e); 
    e.preventDefault(); 
  }
}
```

If you can't do that 👆 because it doesn't give you a large enough scope, another option is to decorate the parent of these list items and then decide what to do inside your list items. Something like:

```javascript
@keydown('up','down')
class List extends React.Component {
  render() {
    ..
    <ListItem { ...props } />
    <ListItem { ...props } />
    ..
  }
}

class ListItem extends ReactComponent {
  @keydownScoped( 'up', 'down' )
  handleKeyDown(e) {
    if (this.props.isSelected) ...
  }
}
```

Do either of those work?

**Comment by strataga** [comment]
After thinking more about it, I think I will only display the child
component when the prop is true from the parent side, otherwise just show a
span. There should only be on of them at a time.

Thanks. I appreciate your help.
