### ISSUE TITLE
findDOMNode on unmounted component

### ISSUE THREAD

**Issue by d-treegardener** [glortho/react-keydown#64]
Hi, I found a bug in your plugin.

From time to time it happens that a component is mounted and directly unmounted.
When this component has a keydown annotation somewhere, it will be added to the store after it was unmounted. If you click then somewhere the _onClick function tries to find this unmounted component.
This causes an Error in IE -> findDOMNode was called on an unmounted component.

The issue is the setTimeout in the onMount function.
```
function onMount( instance ) {
  // have to bump this to next event loop because component mounting routinely
  // preceeds the dom click event that triggered the mount (wtf?)
  setTimeout(() => store.activate( instance ), 0);
  listeners.bindKeys( _onKeyDown );
  listeners.bindClicks( _onClick );
  domHelpers.bindFocusables( instance, store.activate );
}
```

So one solution would be that you remove the setTimeout and call the store.activate directly. Or you could also delay the onUnmount with a setTimeout so that the activate is called before the unmount.

**Comment by glortho** [comment]
Ah yeah this must have started when we switched from bubbling to capturing. Does that make sense to you @salmanm ?

**Comment by salmanm** [comment]
@glortho How could it be related to that event change 🤔 What am I missing?

**Comment by salmanm** [comment]
> When this component has a keydown annotation somewhere, it will be added to the store after it was unmounted

@lemonbutter Are you adding and removing the DOM very quickly?

@glortho This looks to me that it doesn't have anything to do with event change done in https://github.com/glortho/react-keydown/pull/58, but it indeed looks like delaying `store.activate` is causing this.

I see your comments, but couldn't really understand why it didn't work without `setTimeout`

**Comment by d-treegardener** [comment]
@salmanm Yes, after I found the issue, I also refactored my code a bit. But I can't prevent it every where. It's a list which has content but then on mount it will be refreshed and a loading bar is displayed instead.
The list component has a method with left/right keydown to navigate through it.

When I remove the setTimeout it works without issues.

**Comment by glortho** [comment]
@salmanm i believe the smelly `setTimeout` was a patch for cases where a bound component mounted as the result of a click event. in that case, we want the newly mounted component to get dibs on keydown events, even if it's not in the ancestral tree of the click event. for example, i click a button in my sidebar that mounts a key-bound component in a different branch of the view that i want to use the shortcuts for without having to focus on it with a click or tab or whatever.

in the case of *bubbling* we can't rely on doing `store.activate` synchronously because `onMount` may get called before our `onClick` handler at the `document` level, which would then reshuffle the store based on the click event's ancestral tree. in the case of *capturing*, we should be okay without `setTimeout` because our `onClick` handler will run before `onMount` activates any key-bound components (i.e. the most recently mounted key-bound component will be the last one to call `store.activate`, ensuring it gets dibs on keydown events). 

maybe. i'll do some testing without `setTimeout` and see how it goes.

**Comment by salmanm** [comment]
Thanks @glortho for that excellent explanation. I get it now. Yes it makes sense to remove `setTimeout` now 😄

**Comment by glortho** [comment]
ok @salmanm @lemonbutter initial tests removing `setTimeout` have been successful for me. please try 1.9.3 and see if it works predictably for you.

**Comment by d-treegardener** [comment]
The change works for me =) Thanks
