### ISSUE TITLE
Non-decorator pattern.

### ISSUE THREAD

**Issue by yangjiajun2014** [glortho/react-keydown#79]
API & Reference page introduces non-decorator pattern,but it is not supported in the latest version?

**Comment by glortho** [comment]
@yangjiajun2014 It should be working but of course it's possible there is a regression somewhere. Let me know where/how you're trying to use it and we can take a look.

**Comment by yangjiajun2014** [comment]
I just fllow the example in the wiki page and try to import { onMount, onUnmount, setBinding } from 'react-keydown/lib/listeners'.But I can't find this methods  in listeners.

**Comment by glortho** [comment]
Ah okay that path was wrong or out of date in the wiki. It should be
'react-keydown/dist/event_handlers'.
I've corrected the wiki.

**Comment by burnhamrobertp** [comment]
The example non-decorator pattern in the wiki does not work, resulting in a `TypeError: Object(...) is not a function` error if implemented as written.

I was able to get it working by changing the import statements to:
```
import { onMount, onUnmount } from 'react-keydown/dist/event_handlers'
import { setBinding } from 'react-keydown/dist/store'
```

The non-decorator wiki docs have:
```
import { onMount, onUnmount, setBinding } from 'react-keydown/dist/event_handlers';
```

Which throws an error because `setBinding` isn't available inside `event_handlers`. It is available at both `react-keydown/dist` and `react-keydown/dist/store` but the former does not provide proper intellisense functionality, so I used the latter.
