### ISSUE TITLE
`setBinding` warning after upgrading to webpack 4

### ISSUE THREAD

**Issue by EvHaus** [glortho/react-keydown#81]
After upgrading from webpack 3 to webpack 4 the `react-keydown` library is now showing this warning:

```
WARNING in ./node_modules/react-keydown/es/index.js
8:0-37 "export 'setBinding' was not found in './store'
 @ ./node_modules/react-keydown/es/index.js
```

It is possible there's a bad export in the library?

**Comment by af** [comment]
It looks like the issue here is that `/es/index.js` is treating `setBinding` as a named export:

```
export { setBinding } from './store';
```

But in `store.js`, setBinding is actually a method on the default export. You can't destructure a default export like this (though the ES6 syntax implies that you can). The fix for this might be as simple as adding 

```
export const setBinding = Store.setBinding;
```

 to the bottom of `/es/store.js`, as `setBinding()` doesn't appear to use any context from `Store`.

**Comment by glortho** [comment]
Okay please see if 1.9.7 works for you and let me know!

**Comment by EvHaus** [comment]
1.9.7 did the trick. Thanks!
